import { createTransaction } from '../domain/transaction';

/**
 * Demo transactions for development and testing purposes only.
 * These are not loaded in production.
 */
export function createDemoTransactions() {
  return [
    createTransaction({
      date: '2026-01-01',
      type: 'income',
      amount: 3200,
      purpose: 'Gehalt Januar',
      category: 'Gehalt',
      partner: 'Arbeitgeber GmbH',
      recurrence: 'monthly',
    }),
    createTransaction({
      date: '2026-01-01',
      type: 'expense',
      amount: 950,
      purpose: 'Monatsmiete',
      category: 'Wohnen',
      partner: 'Vermieter',
      recurrence: 'monthly',
    }),
    createTransaction({
      date: '2026-01-01',
      type: 'expense',
      amount: 49.99,
      purpose: 'Strom',
      category: 'Nebenkosten',
      partner: 'Stadtwerke',
      recurrence: 'monthly',
    }),
    createTransaction({
      date: '2026-01-01',
      type: 'expense',
      amount: 19.99,
      purpose: 'Internetvertrag',
      category: 'Telekommunikation',
      partner: 'Telefonanbieter GmbH',
      recurrence: 'monthly',
    }),
    createTransaction({
      date: '2026-01-01',
      type: 'expense',
      amount: 89.50,
      purpose: 'KFZ-Versicherung',
      category: 'Versicherung',
      partner: 'Versicherung AG',
      recurrence: 'monthly',
    }),
    createTransaction({
      date: '2026-01-07',
      type: 'expense',
      amount: 64.30,
      purpose: 'Wocheneinkauf',
      category: 'Lebensmittel',
      partner: 'Supermarkt',
      recurrence: 'once',
    }),
    createTransaction({
      date: '2026-01-14',
      type: 'expense',
      amount: 58.90,
      purpose: 'Wocheneinkauf',
      category: 'Lebensmittel',
      partner: 'Supermarkt',
      recurrence: 'once',
    }),
    createTransaction({
      date: '2026-02-03',
      type: 'expense',
      amount: 120.00,
      purpose: 'Arztbesuch',
      category: 'Gesundheit',
      partner: 'Arztpraxis',
      recurrence: 'once',
    }),
    createTransaction({
      date: '2026-02-20',
      type: 'expense',
      amount: 250.00,
      purpose: 'Winterjacke',
      category: 'Kleidung',
      partner: 'Bekleidungsgeschäft',
      recurrence: 'once',
    }),
    createTransaction({
      date: '2026-03-15',
      type: 'income',
      amount: 500.00,
      purpose: 'Steuerrückerstattung',
      category: 'Sonstiges',
      partner: 'Finanzamt',
      recurrence: 'once',
    }),
    createTransaction({
      date: '2026-04-01',
      type: 'expense',
      amount: 45.00,
      purpose: 'Streaming-Dienst',
      category: 'Freizeit',
      partner: 'Streaming AG',
      recurrence: 'monthly',
    }),
    createTransaction({
      date: '2026-05-07',
      type: 'expense',
      amount: 54.90,
      purpose: 'Wocheneinkauf',
      category: 'Lebensmittel',
      partner: 'Supermarkt',
      recurrence: 'once',
    }),
    createTransaction({
      date: '2026-05-20',
      type: 'expense',
      amount: 180.00,
      purpose: 'Restaurantbesuch',
      category: 'Freizeit',
      partner: 'Restaurant',
      recurrence: 'once',
    }),
    createTransaction({
      date: '2026-06-10',
      type: 'expense',
      amount: 320.00,
      purpose: 'Urlaub Anzahlung',
      category: 'Urlaub',
      partner: 'Reisebüro',
      recurrence: 'once',
    }),
  ];
}
